App\Security\Domain\Model\User\User:
  type: entity
  table: user
  indexes:
    id:
      columns: [ id ]
  id:
    id:
      type: user_id
      length: 36
      options:
        fixed: true
      column: id
  fields:
    email:
      type: string
      column: email
      unique: true
    password:
      type: string
      column: password
    roles:
      type: array
      column: roles
    salt:
      type: string
      nullable: true
      column: salt
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
