openapi: "3.0.0"
info:
  title: Hexagonal API Example
  version: "1.0"
servers:
  - url: '/api/v1'

paths:
  /users/register:
    $ref: 'Security/User/paths.yaml#/createUser'

  /users/auth:
    $ref: 'Security/User/paths.yaml#/authenticateUser'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
