openapi: "3.0.0"
info:
  title: Hexagonal API Example
  version: "1.0"
servers:
  - url: '/api/v1'

paths:
  /users/register:
    $ref: 'Security/User/paths.yaml#/createUser'

  /users:
    $ref: 'Security/User/paths.yaml#/updateUser'

  /users/auth:
    $ref: 'Security/User/paths.yaml#/authenticateUser'

  /movies:
    $ref: 'Core/Movie/paths.yaml#/moviesCRUD'

  /movies/{movieId}:
    $ref: 'Core/Movie/paths.yaml#/getMovieById'

  /movies/{movieId}/add-genre:
    $ref: 'Core/Movie/paths.yaml#/addGenreToMovie'

  /genres:
    $ref: 'Core/Genre/paths.yaml#/genresCRUD'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
