openapi: "3.0.0"
info:
  title: Hexagonal API Example
  version: "1.0"
servers:
  - url: '/api/v1'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
