services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Security\Infrastructure\UI\Http\Controller\:
    resource: '../../../../UI/Http/Controller/*'
    public: true
    tags: [ 'controller.service_arguments' ]

  App\Security\Application\Query\:
    resource: '../../../../../Application/Query/*/*/*Handler.php'

  App\Security\Application\Command\:
    resource: '../../../../../Application/Command/*/*/*'
    exclude: '../../../../../Application/Command/*/*/*Command.php'
    tags:
      - { name: 'tactician.handler', typehints: true }

  App\Security\Application\Service\:
    resource: '../../../../../Application/Service/*'

  App\Security\Infrastructure\Domain\:
    resource: '../../../../Domain/*'
    exclude: '../../../../Domain/Hydrator/*'

  App\Security\Infrastructure\UI\Http\IO\:
    resource: '../../../../UI/Http/IO/*'

  App\Security\Infrastructure\Framework\Symfony\Security\JWTUserProvider: ~
  App\Security\Domain\Model\User\UserRepositoryInterface: '@App\Security\Infrastructure\Domain\Model\User\DoctrineUserRepository'
  App\Shared\Infrastructure\UI\Http\IO\Input\User\CreateUserTransformer: ~


