create_movie:
  path: /movies
  methods: [POST]
  defaults:
    _controller: App\Core\Infrastructure\UI\Http\Controller\Movie\CreateMovieController

list_movies:
  path: /movies
  methods: [GET]
  defaults:
    _controller: App\Core\Infrastructure\UI\Http\Controller\Movie\ListMoviesController

get_movie:
  path: /movies/{movieId}
  methods: [GET]
  defaults:
    _controller: App\Core\Infrastructure\UI\Http\Controller\Movie\GetMovieByIdController

add_genre_to_movie:
  path: /movies/{movieId}/add-genre
  methods: [POST]
  defaults:
    _controller: App\Core\Infrastructure\UI\Http\Controller\Movie\AddGenreToMovieController
