services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\Core\Application\Query\:
    resource: '../../../../../Application/Query/*/*/*Handler.php'

  App\Core\Application\UseCase\:
    resource: '../../../../../Application/UseCase/*/*/*Handler.php'

  App\Core\Application\Command\:
    resource: '../../../../../Application/Command/*/*/*Handler.php'
    tags:
      - { name: 'tactician.handler', typehints: true }

  App\Core\Infrastructure\Domain\:
    resource: '../../../../Domain/*'
    exclude: '../../../../Domain/Hydrator/*'

  App\Core\Infrastructure\UI\Http\Controller\:
    resource: '../../../../UI/Http/Controller/*'
    tags: ['controller.service_arguments']

  App\Core\Infrastructure\UI\Http\IO\:
    resource: '../../../../UI/Http/IO/*'

  App\Core\Domain\Model\Genre\GenreViewInterface: '@App\Core\Infrastructure\Domain\Model\Genre\MySQLGenreView'