services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Core\Application\Query\:
    public: true
    resource: '../../../../../Application/Query/*/*/*Handler.php'

  App\Core\Application\Listener\:
    resource: '../../../../../Application/Listener/*'

  App\Core\Application\UseCase\:
    resource: '../../../../../Application/UseCase/*/*/*Handler.php'

  App\Core\Application\Command\:
    resource: '../../../../../Application/Command/*/*/*Handler.php'
    tags:
      - { name: 'tactician.handler', typehints: true }

  App\Core\Infrastructure\Domain\:
    resource: '../../../../Domain/*'
    exclude: '../../../../Domain/Hydrator/*'

  App\Core\Infrastructure\UI\Http\Controller\:
    resource: '../../../../UI/Http/Controller/*'
    public: true
    tags: ['controller.service_arguments']

  App\Core\Infrastructure\UI\Http\IO\Input\:
    resource: '../../../../UI/Http/IO/Input/*'

  App\Core\Domain\Model\Genre\GenreViewInterface: '@App\Core\Infrastructure\Domain\Model\Genre\MySQLGenreView'
  App\Core\Domain\Model\Genre\GenreRepositoryInterface: '@App\Core\Infrastructure\Domain\Model\Genre\MySQLGenreRepository'
  App\Core\Domain\Model\Movie\MovieViewInterface: '@App\Core\Infrastructure\Domain\Model\Movie\MySQLMovieView'
  App\Core\Domain\Model\Movie\MovieRepositoryInterface: '@App\Core\Infrastructure\Domain\Model\Movie\MySQLMovieRepository'