open_api:
  path: /api/doc/{version}
  methods: [GET]
  defaults:
    _controller: App\OpenApi\OpenApiController

open_api_spec:
  path: /api/doc/spec/{version}
  methods: [GET]
  defaults:
    _controller: App\OpenApi\SpecController

skeleton:
  prefix: '/api/v1'
  resource: '../src/Skeleton/Infrastructure/Framework/Symfony/Resources/config/routes.yaml'

security:
  prefix: '/api/v1'
  resource: '../src/Security/Infrastructure/Framework/Symfony/Resources/config/routes.yaml'