services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Shared\Infrastructure\Security\GenericApplicantProvider: ~
  App\Shared\Infrastructure\UI\Http\IO\Input\BaseInputTransformer: ~
  App\Shared\Infrastructure\UI\Http\IO\Input\JsonValidator: ~